import { ContinentType } from "./continents";
import { LanguageCodes } from "./languages";

export interface Country {
  name: string;
  native: string;
  phone: string;
  continent: ContinentType | "NA";
  capital: string;
  currency: string;
  languages: readonly LanguageCodes[];
  code: string;
  code3: string;
  emoji: string;
  emojiU: string;
}

export const COUNTRIES = [
  {
    name: "Andorra",
    native: "Andorra",
    phone: "376",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Andorra la Vella",
    currency: "EUR",
    languages: ["ca"],
    code: "AD",
    code3: "AND",
    emoji: "🇦🇩",
    emojiU: "U+1F1E6 U+1F1E9",
  },
  {
    name: "United Arab Emirates",
    native: "دولة الإمارات العربية المتحدة",
    phone: "971",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Abu Dhabi",
    currency: "AED",
    languages: ["ar"],
    code: "AE",
    code3: "ARE",
    emoji: "🇦🇪",
    emojiU: "U+1F1E6 U+1F1EA",
  },
  {
    name: "Afghanistan",
    native: "افغانستان",
    phone: "93",
    continent: { code: "AS", region: "Southern Asia" },
    capital: "Kabul",
    currency: "AFN",
    languages: ["ps", "uz", "tk"],
    code: "AF",
    code3: "AFG",
    emoji: "🇦🇫",
    emojiU: "U+1F1E6 U+1F1EB",
  },
  {
    name: "Antigua and Barbuda",
    native: "Antigua and Barbuda",
    phone: "1268",
    continent: "NA",
    capital: "Saint John's",
    currency: "XCD",
    languages: ["en"],
    code: "AG",
    code3: "ATG",
    emoji: "🇦🇬",
    emojiU: "U+1F1E6 U+1F1EC",
  },
  {
    name: "Anguilla",
    native: "Anguilla",
    phone: "1264",
    continent: "NA",
    capital: "The Valley",
    currency: "XCD",
    languages: ["en"],
    code: "AI",
    code3: "AIA",
    emoji: "🇦🇮",
    emojiU: "U+1F1E6 U+1F1EE",
  },
  {
    name: "Albania",
    native: "Shqipëria",
    phone: "355",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Tirana",
    currency: "ALL",
    languages: ["sq"],
    code: "AL",
    code3: "ALB",
    emoji: "🇦🇱",
    emojiU: "U+1F1E6 U+1F1F1",
  },
  {
    name: "Armenia",
    native: "Հայաստան",
    phone: "374",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Yerevan",
    currency: "AMD",
    languages: ["hy", "ru"],
    code: "AM",
    code3: "ARM",
    emoji: "🇦🇲",
    emojiU: "U+1F1E6 U+1F1F2",
  },
  {
    name: "Angola",
    native: "Angola",
    phone: "244",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "Luanda",
    currency: "AOA",
    languages: ["pt"],
    code: "AO",
    code3: "AGO",
    emoji: "🇦🇴",
    emojiU: "U+1F1E6 U+1F1F4",
  },
  {
    name: "Antarctica",
    native: "Antarctica",
    phone: "672",
    continent: { code: "AN", region: "Antarctica" },
    capital: "",
    currency: "",
    languages: [],
    code: "AQ",
    code3: "ATA",
    emoji: "🇦🇶",
    emojiU: "U+1F1E6 U+1F1F6",
  },
  {
    name: "Argentina",
    native: "Argentina",
    phone: "54",
    continent: { code: "SA", region: "South America" },
    capital: "Buenos Aires",
    currency: "ARS",
    languages: ["es", "gn"],
    code: "AR",
    code3: "ARG",
    emoji: "🇦🇷",
    emojiU: "U+1F1E6 U+1F1F7",
  },
  {
    name: "American Samoa",
    native: "American Samoa",
    phone: "1684",
    continent: { code: "OC", region: "Oceania" },
    capital: "Pago Pago",
    currency: "USD",
    languages: ["en", "sm"],
    code: "AS",
    code3: "ASM",
    emoji: "🇦🇸",
    emojiU: "U+1F1E6 U+1F1F8",
  },
  {
    name: "Austria",
    native: "Österreich",
    phone: "43",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Vienna",
    currency: "EUR",
    languages: ["de"],
    code: "AT",
    code3: "AUT",
    emoji: "🇦🇹",
    emojiU: "U+1F1E6 U+1F1F9",
  },
  {
    name: "Australia",
    native: "Australia",
    phone: "61",
    continent: { code: "OC", region: "Oceania" },
    capital: "Canberra",
    currency: "AUD",
    languages: ["en"],
    code: "AU",
    code3: "AUS",
    emoji: "🇦🇺",
    emojiU: "U+1F1E6 U+1F1FA",
  },
  {
    name: "Aruba",
    native: "Aruba",
    phone: "297",
    continent: "NA",
    capital: "Oranjestad",
    currency: "AWG",
    languages: ["nl", "pa"],
    code: "AW",
    code3: "ABW",
    emoji: "🇦🇼",
    emojiU: "U+1F1E6 U+1F1FC",
  },
  {
    name: "Åland",
    native: "Åland",
    phone: "358",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Mariehamn",
    currency: "EUR",
    languages: ["sv"],
    code: "AX",
    code3: "ALA",
    emoji: "🇦🇽",
    emojiU: "U+1F1E6 U+1F1FD",
  },
  {
    name: "Azerbaijan",
    native: "Azərbaycan",
    phone: "994",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Baku",
    currency: "AZN",
    languages: ["az"],
    code: "AZ",
    code3: "AZE",
    emoji: "🇦🇿",
    emojiU: "U+1F1E6 U+1F1FF",
  },
  {
    name: "Bosnia and Herzegovina",
    native: "Bosna i Hercegovina",
    phone: "387",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Sarajevo",
    currency: "BAM",
    languages: ["bs", "hr", "sr"],
    code: "BA",
    code3: "BIH",
    emoji: "🇧🇦",
    emojiU: "U+1F1E7 U+1F1E6",
  },
  {
    name: "Barbados",
    native: "Barbados",
    phone: "1246",
    continent: "NA",
    capital: "Bridgetown",
    currency: "BBD",
    languages: ["en"],
    code: "BB",
    code3: "BRB",
    emoji: "🇧🇧",
    emojiU: "U+1F1E7 U+1F1E7",
  },
  {
    name: "Bangladesh",
    native: "Bangladesh",
    phone: "880",
    continent: { code: "AS", region: "Southern Asia" },
    capital: "Dhaka",
    currency: "BDT",
    languages: ["bn"],
    code: "BD",
    code3: "BGD",
    emoji: "🇧🇩",
    emojiU: "U+1F1E7 U+1F1E9",
  },
  {
    name: "Belgium",
    native: "België",
    phone: "32",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Brussels",
    currency: "EUR",
    languages: ["nl", "fr", "de"],
    code: "BE",
    code3: "BEL",
    emoji: "🇧🇪",
    emojiU: "U+1F1E7 U+1F1EA",
  },
  {
    name: "Burkina Faso",
    native: "Burkina Faso",
    phone: "226",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Ouagadougou",
    currency: "XOF",
    languages: ["fr", "ff"],
    code: "BF",
    code3: "BFA",
    emoji: "🇧🇫",
    emojiU: "U+1F1E7 U+1F1EB",
  },
  {
    name: "Bulgaria",
    native: "България",
    phone: "359",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Sofia",
    currency: "BGN",
    languages: ["bg"],
    code: "BG",
    code3: "BGR",
    emoji: "🇧🇬",
    emojiU: "U+1F1E7 U+1F1EC",
  },
  {
    name: "Bahrain",
    native: "‏البحرين",
    phone: "973",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Manama",
    currency: "BHD",
    languages: ["ar"],
    code: "BH",
    code3: "BHR",
    emoji: "🇧🇭",
    emojiU: "U+1F1E7 U+1F1ED",
  },
  {
    name: "Burundi",
    native: "Burundi",
    phone: "257",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Bujumbura",
    currency: "BIF",
    languages: ["fr", "rn"],
    code: "BI",
    code3: "BDI",
    emoji: "🇧🇮",
    emojiU: "U+1F1E7 U+1F1EE",
  },
  {
    name: "Benin",
    native: "Bénin",
    phone: "229",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Porto-Novo",
    currency: "XOF",
    languages: ["fr"],
    code: "BJ",
    code3: "BEN",
    emoji: "🇧🇯",
    emojiU: "U+1F1E7 U+1F1EF",
  },
  {
    name: "Saint Barthélemy",
    native: "Saint-Barthélemy",
    phone: "590",
    continent: "NA",
    capital: "Gustavia",
    currency: "EUR",
    languages: ["fr"],
    code: "BL",
    code3: "BLM",
    emoji: "🇧🇱",
    emojiU: "U+1F1E7 U+1F1F1",
  },
  {
    name: "Bermuda",
    native: "Bermuda",
    phone: "1441",
    continent: "NA",
    capital: "Hamilton",
    currency: "BMD",
    languages: ["en"],
    code: "BM",
    code3: "BMU",
    emoji: "🇧🇲",
    emojiU: "U+1F1E7 U+1F1F2",
  },
  {
    name: "Brunei",
    native: "Negara Brunei Darussalam",
    phone: "673",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Bandar Seri Begawan",
    currency: "BND",
    languages: ["ms"],
    code: "BN",
    code3: "BRN",
    emoji: "🇧🇳",
    emojiU: "U+1F1E7 U+1F1F3",
  },
  {
    name: "Bolivia",
    native: "Bolivia",
    phone: "591",
    continent: { code: "SA", region: "South America" },
    capital: "Sucre",
    currency: "BOB,BOV",
    languages: ["es", "ay", "qu"],
    code: "BO",
    code3: "BOL",
    emoji: "🇧🇴",
    emojiU: "U+1F1E7 U+1F1F4",
  },
  {
    name: "Bonaire",
    native: "Bonaire",
    phone: "5997",
    continent: "NA",
    capital: "Kralendijk",
    currency: "USD",
    languages: ["nl"],
    code: "BQ",
    code3: "BES",
    emoji: "🇧🇶",
    emojiU: "U+1F1E7 U+1F1F6",
  },
  {
    name: "Brazil",
    native: "Brasil",
    phone: "55",
    continent: { code: "SA", region: "South America" },
    capital: "Brasília",
    currency: "BRL",
    languages: ["pt"],
    code: "BR",
    code3: "BRA",
    emoji: "🇧🇷",
    emojiU: "U+1F1E7 U+1F1F7",
  },
  {
    name: "Bahamas",
    native: "Bahamas",
    phone: "1242",
    continent: "NA",
    capital: "Nassau",
    currency: "BSD",
    languages: ["en"],
    code: "BS",
    code3: "BHS",
    emoji: "🇧🇸",
    emojiU: "U+1F1E7 U+1F1F8",
  },
  {
    name: "Bhutan",
    native: "ʼbrug-yul",
    phone: "975",
    continent: { code: "AS", region: "Southern Asia" },
    capital: "Thimphu",
    currency: "BTN,INR",
    languages: ["dz"],
    code: "BT",
    code3: "BTN",
    emoji: "🇧🇹",
    emojiU: "U+1F1E7 U+1F1F9",
  },
  {
    name: "Bouvet Island",
    native: "Bouvetøya",
    phone: "47",
    continent: { code: "AN", region: "Antarctica" },
    capital: "",
    currency: "NOK",
    languages: ["no", "nb", "nn"],
    code: "BV",
    code3: "BVT",
    emoji: "🇧🇻",
    emojiU: "U+1F1E7 U+1F1FB",
  },
  {
    name: "Botswana",
    native: "Botswana",
    phone: "267",
    continent: { code: "AF", region: "Southern Africa" },
    capital: "Gaborone",
    currency: "BWP",
    languages: ["en", "tn"],
    code: "BW",
    code3: "BWA",
    emoji: "🇧🇼",
    emojiU: "U+1F1E7 U+1F1FC",
  },
  {
    name: "Belarus",
    native: "Белару́сь",
    phone: "375",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Minsk",
    currency: "BYN",
    languages: ["be", "ru"],
    code: "BY",
    code3: "BLR",
    emoji: "🇧🇾",
    emojiU: "U+1F1E7 U+1F1FE",
  },
  {
    name: "Belize",
    native: "Belize",
    phone: "501",
    continent: "NA",
    capital: "Belmopan",
    currency: "BZD",
    languages: ["en", "es"],
    code: "BZ",
    code3: "BLZ",
    emoji: "🇧🇿",
    emojiU: "U+1F1E7 U+1F1FF",
  },
  {
    name: "Canada",
    native: "Canada",
    phone: "1",
    continent: "NA",
    capital: "Ottawa",
    currency: "CAD",
    languages: ["en", "fr"],
    code: "CA",
    code3: "CAN",
    emoji: "🇨🇦",
    emojiU: "U+1F1E8 U+1F1E6",
  },
  {
    name: "Cocos [Keeling] Islands",
    native: "Cocos (Keeling) Islands",
    phone: "61",
    continent: { code: "OC", region: "Oceania" },
    capital: "West Island",
    currency: "AUD",
    languages: ["en"],
    code: "CC",
    code3: "CCK",
    emoji: "🇨🇨",
    emojiU: "U+1F1E8 U+1F1E8",
  },
  {
    name: "Democratic Republic of the Congo",
    native: "République démocratique du Congo",
    phone: "243",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "Kinshasa",
    currency: "CDF",
    languages: ["fr", "ln", "kg", "sw", "lu"],
    code: "CD",
    code3: "COD",
    emoji: "🇨🇩",
    emojiU: "U+1F1E8 U+1F1E9",
  },
  {
    name: "Central African Republic",
    native: "Ködörösêse tî Bêafrîka",
    phone: "236",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "Bangui",
    currency: "XAF",
    languages: ["fr", "sg"],
    code: "CF",
    code3: "CAF",
    emoji: "🇨🇫",
    emojiU: "U+1F1E8 U+1F1EB",
  },
  {
    name: "Republic of the Congo",
    native: "République du Congo",
    phone: "242",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "Brazzaville",
    currency: "XAF",
    languages: ["fr", "ln"],
    code: "CG",
    code3: "COG",
    emoji: "🇨🇬",
    emojiU: "U+1F1E8 U+1F1EC",
  },
  {
    name: "Switzerland",
    native: "Schweiz",
    phone: "41",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Bern",
    currency: "CHE,CHF,CHW",
    languages: ["de", "fr", "it"],
    code: "CH",
    code3: "CHE",
    emoji: "🇨🇭",
    emojiU: "U+1F1E8 U+1F1ED",
  },
  {
    name: "Ivory Coast",
    native: "Côte d'Ivoire",
    phone: "225",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Yamoussoukro",
    currency: "XOF",
    languages: ["fr"],
    code: "CI",
    code3: "CIV",
    emoji: "🇨🇮",
    emojiU: "U+1F1E8 U+1F1EE",
  },
  {
    name: "Cook Islands",
    native: "Cook Islands",
    phone: "682",
    continent: { code: "OC", region: "Oceania" },
    capital: "Avarua",
    currency: "NZD",
    languages: ["en"],
    code: "CK",
    code3: "COK",
    emoji: "🇨🇰",
    emojiU: "U+1F1E8 U+1F1F0",
  },
  {
    name: "Chile",
    native: "Chile",
    phone: "56",
    continent: { code: "SA", region: "South America" },
    capital: "Santiago",
    currency: "CLF,CLP",
    languages: ["es"],
    code: "CL",
    code3: "CHL",
    emoji: "🇨🇱",
    emojiU: "U+1F1E8 U+1F1F1",
  },
  {
    name: "Cameroon",
    native: "Cameroon",
    phone: "237",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "Yaoundé",
    currency: "XAF",
    languages: ["en", "fr"],
    code: "CM",
    code3: "CMR",
    emoji: "🇨🇲",
    emojiU: "U+1F1E8 U+1F1F2",
  },
  {
    name: "China",
    native: "中国",
    phone: "86",
    continent: { code: "AS", region: "Eastern Asia" },
    capital: "Beijing",
    currency: "CNY",
    languages: ["zh"],
    code: "CN",
    code3: "CHN",
    emoji: "🇨🇳",
    emojiU: "U+1F1E8 U+1F1F3",
  },
  {
    name: "Colombia",
    native: "Colombia",
    phone: "57",
    continent: { code: "SA", region: "South America" },
    capital: "Bogotá",
    currency: "COP",
    languages: ["es"],
    code: "CO",
    code3: "COL",
    emoji: "🇨🇴",
    emojiU: "U+1F1E8 U+1F1F4",
  },
  {
    name: "Costa Rica",
    native: "Costa Rica",
    phone: "506",
    continent: "NA",
    capital: "San José",
    currency: "CRC",
    languages: ["es"],
    code: "CR",
    code3: "CRI",
    emoji: "🇨🇷",
    emojiU: "U+1F1E8 U+1F1F7",
  },
  {
    name: "Cuba",
    native: "Cuba",
    phone: "53",
    continent: "NA",
    capital: "Havana",
    currency: "CUC,CUP",
    languages: ["es"],
    code: "CU",
    code3: "CUB",
    emoji: "🇨🇺",
    emojiU: "U+1F1E8 U+1F1FA",
  },
  {
    name: "Cape Verde",
    native: "Cabo Verde",
    phone: "238",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Praia",
    currency: "CVE",
    languages: ["pt"],
    code: "CV",
    code3: "CPV",
    emoji: "🇨🇻",
    emojiU: "U+1F1E8 U+1F1FB",
  },
  {
    name: "Curacao",
    native: "Curaçao",
    phone: "5999",
    continent: "NA",
    capital: "Willemstad",
    currency: "ANG",
    languages: ["nl", "pa", "en"],
    code: "CW",
    code3: "CUW",
    emoji: "🇨🇼",
    emojiU: "U+1F1E8 U+1F1FC",
  },
  {
    name: "Christmas Island",
    native: "Christmas Island",
    phone: "61",
    continent: { code: "OC", region: "Oceania" },
    capital: "Flying Fish Cove",
    currency: "AUD",
    languages: ["en"],
    code: "CX",
    code3: "CXR",
    emoji: "🇨🇽",
    emojiU: "U+1F1E8 U+1F1FD",
  },
  {
    name: "Cyprus",
    native: "Κύπρος",
    phone: "357",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Nicosia",
    currency: "EUR",
    languages: ["el", "tr", "hy"],
    code: "CY",
    code3: "CYP",
    emoji: "🇨🇾",
    emojiU: "U+1F1E8 U+1F1FE",
  },
  {
    name: "Czech Republic",
    native: "Česká republika",
    phone: "420",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Prague",
    currency: "CZK",
    languages: ["cs", "sk"],
    code: "CZ",
    code3: "CZE",
    emoji: "🇨🇿",
    emojiU: "U+1F1E8 U+1F1FF",
  },
  {
    name: "Germany",
    native: "Deutschland",
    phone: "49",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Berlin",
    currency: "EUR",
    languages: ["de"],
    code: "DE",
    code3: "DEU",
    emoji: "🇩🇪",
    emojiU: "U+1F1E9 U+1F1EA",
  },
  {
    name: "Djibouti",
    native: "Djibouti",
    phone: "253",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Djibouti",
    currency: "DJF",
    languages: ["fr", "ar"],
    code: "DJ",
    code3: "DJI",
    emoji: "🇩🇯",
    emojiU: "U+1F1E9 U+1F1EF",
  },
  {
    name: "Denmark",
    native: "Danmark",
    phone: "45",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Copenhagen",
    currency: "DKK",
    languages: ["da"],
    code: "DK",
    code3: "DNK",
    emoji: "🇩🇰",
    emojiU: "U+1F1E9 U+1F1F0",
  },
  {
    name: "Dominica",
    native: "Dominica",
    phone: "1767",
    continent: "NA",
    capital: "Roseau",
    currency: "XCD",
    languages: ["en"],
    code: "DM",
    code3: "DMA",
    emoji: "🇩🇲",
    emojiU: "U+1F1E9 U+1F1F2",
  },
  {
    name: "Dominican Republic",
    native: "República Dominicana",
    phone: "1809,1829,1849",
    continent: "NA",
    capital: "Santo Domingo",
    currency: "DOP",
    languages: ["es"],
    code: "DO",
    code3: "DOM",
    emoji: "🇩🇴",
    emojiU: "U+1F1E9 U+1F1F4",
  },
  {
    name: "Algeria",
    native: "الجزائر",
    phone: "213",
    continent: { code: "AF", region: "Northern Africa" },
    capital: "Algiers",
    currency: "DZD",
    languages: ["ar"],
    code: "DZ",
    code3: "DZA",
    emoji: "🇩🇿",
    emojiU: "U+1F1E9 U+1F1FF",
  },
  {
    name: "Ecuador",
    native: "Ecuador",
    phone: "593",
    continent: { code: "SA", region: "South America" },
    capital: "Quito",
    currency: "USD",
    languages: ["es"],
    code: "EC",
    code3: "ECU",
    emoji: "🇪🇨",
    emojiU: "U+1F1EA U+1F1E8",
  },
  {
    name: "Estonia",
    native: "Eesti",
    phone: "372",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Tallinn",
    currency: "EUR",
    languages: ["et"],
    code: "EE",
    code3: "EST",
    emoji: "🇪🇪",
    emojiU: "U+1F1EA U+1F1EA",
  },
  {
    name: "Egypt",
    native: "مصر‎",
    phone: "20",
    continent: { code: "AF", region: "Northern Africa" },
    capital: "Cairo",
    currency: "EGP",
    languages: ["ar"],
    code: "EG",
    code3: "EGY",
    emoji: "🇪🇬",
    emojiU: "U+1F1EA U+1F1EC",
  },
  {
    name: "Western Sahara",
    native: "الصحراء الغربية",
    phone: "212",
    continent: { code: "AF", region: "Northern Africa" },
    capital: "El Aaiún",
    currency: "MAD,DZD,MRU",
    languages: ["es"],
    code: "EH",
    code3: "ESH",
    emoji: "🇪🇭",
    emojiU: "U+1F1EA U+1F1ED",
  },
  {
    name: "Eritrea",
    native: "ኤርትራ",
    phone: "291",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Asmara",
    currency: "ERN",
    languages: ["ti", "ar", "en"],
    code: "ER",
    code3: "ERI",
    emoji: "🇪🇷",
    emojiU: "U+1F1EA U+1F1F7",
  },
  {
    name: "Spain",
    native: "España",
    phone: "34",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Madrid",
    currency: "EUR",
    languages: ["es", "eu", "ca", "gl", "oc"],
    code: "ES",
    code3: "ESP",
    emoji: "🇪🇸",
    emojiU: "U+1F1EA U+1F1F8",
  },
  {
    name: "Ethiopia",
    native: "ኢትዮጵያ",
    phone: "251",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Addis Ababa",
    currency: "ETB",
    languages: ["am"],
    code: "ET",
    code3: "ETH",
    emoji: "🇪🇹",
    emojiU: "U+1F1EA U+1F1F9",
  },
  {
    name: "Finland",
    native: "Suomi",
    phone: "358",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Helsinki",
    currency: "EUR",
    languages: ["fi", "sv"],
    code: "FI",
    code3: "FIN",
    emoji: "🇫🇮",
    emojiU: "U+1F1EB U+1F1EE",
  },
  {
    name: "Fiji",
    native: "Fiji",
    phone: "679",
    continent: { code: "OC", region: "Oceania" },
    capital: "Suva",
    currency: "FJD",
    languages: ["en", "fj", "hi", "ur"],
    code: "FJ",
    code3: "FJI",
    emoji: "🇫🇯",
    emojiU: "U+1F1EB U+1F1EF",
  },
  {
    name: "Falkland Islands",
    native: "Falkland Islands",
    phone: "500",
    continent: { code: "SA", region: "South America" },
    capital: "Stanley",
    currency: "FKP",
    languages: ["en"],
    code: "FK",
    code3: "FLK",
    emoji: "🇫🇰",
    emojiU: "U+1F1EB U+1F1F0",
  },
  {
    name: "Micronesia",
    native: "Micronesia",
    phone: "691",
    continent: { code: "OC", region: "Oceania" },
    capital: "Palikir",
    currency: "USD",
    languages: ["en"],
    code: "FM",
    code3: "FSM",
    emoji: "🇫🇲",
    emojiU: "U+1F1EB U+1F1F2",
  },
  {
    name: "Faroe Islands",
    native: "Føroyar",
    phone: "298",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Tórshavn",
    currency: "DKK",
    languages: ["fo"],
    code: "FO",
    code3: "FRO",
    emoji: "🇫🇴",
    emojiU: "U+1F1EB U+1F1F4",
  },
  {
    name: "France",
    native: "France",
    phone: "33",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Paris",
    currency: "EUR",
    languages: ["fr"],
    code: "FR",
    code3: "FRA",
    emoji: "🇫🇷",
    emojiU: "U+1F1EB U+1F1F7",
  },
  {
    name: "Gabon",
    native: "Gabon",
    phone: "241",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "Libreville",
    currency: "XAF",
    languages: ["fr"],
    code: "GA",
    code3: "GAB",
    emoji: "🇬🇦",
    emojiU: "U+1F1EC U+1F1E6",
  },
  {
    name: "United Kingdom",
    native: "United Kingdom",
    phone: "44",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "London",
    currency: "GBP",
    languages: ["en"],
    code: "GB",
    code3: "GBR",
    emoji: "🇬🇧",
    emojiU: "U+1F1EC U+1F1E7",
  },
  {
    name: "Grenada",
    native: "Grenada",
    phone: "1473",
    continent: "NA",
    capital: "St. George's",
    currency: "XCD",
    languages: ["en"],
    code: "GD",
    code3: "GRD",
    emoji: "🇬🇩",
    emojiU: "U+1F1EC U+1F1E9",
  },
  {
    name: "Georgia",
    native: "საქართველო",
    phone: "995",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Tbilisi",
    currency: "GEL",
    languages: ["ka"],
    code: "GE",
    code3: "GEO",
    emoji: "🇬🇪",
    emojiU: "U+1F1EC U+1F1EA",
  },
  {
    name: "French Guiana",
    native: "Guyane française",
    phone: "594",
    continent: { code: "SA", region: "South America" },
    capital: "Cayenne",
    currency: "EUR",
    languages: ["fr"],
    code: "GF",
    code3: "GUF",
    emoji: "🇬🇫",
    emojiU: "U+1F1EC U+1F1EB",
  },
  {
    name: "Guernsey",
    native: "Guernsey",
    phone: "44",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "St. Peter Port",
    currency: "GBP",
    languages: ["en", "fr"],
    code: "GG",
    code3: "GGY",
    emoji: "🇬🇬",
    emojiU: "U+1F1EC U+1F1EC",
  },
  {
    name: "Ghana",
    native: "Ghana",
    phone: "233",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Accra",
    currency: "GHS",
    languages: ["en"],
    code: "GH",
    code3: "GHA",
    emoji: "🇬🇭",
    emojiU: "U+1F1EC U+1F1ED",
  },
  {
    name: "Gibraltar",
    native: "Gibraltar",
    phone: "350",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Gibraltar",
    currency: "GIP",
    languages: ["en"],
    code: "GI",
    code3: "GIB",
    emoji: "🇬🇮",
    emojiU: "U+1F1EC U+1F1EE",
  },
  {
    name: "Greenland",
    native: "Kalaallit Nunaat",
    phone: "299",
    continent: "NA",
    capital: "Nuuk",
    currency: "DKK",
    languages: ["kl"],
    code: "GL",
    code3: "GRL",
    emoji: "🇬🇱",
    emojiU: "U+1F1EC U+1F1F1",
  },
  {
    name: "Gambia",
    native: "Gambia",
    phone: "220",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Banjul",
    currency: "GMD",
    languages: ["en"],
    code: "GM",
    code3: "GMB",
    emoji: "🇬🇲",
    emojiU: "U+1F1EC U+1F1F2",
  },
  {
    name: "Guinea",
    native: "Guinée",
    phone: "224",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Conakry",
    currency: "GNF",
    languages: ["fr", "ff"],
    code: "GN",
    code3: "GIN",
    emoji: "🇬🇳",
    emojiU: "U+1F1EC U+1F1F3",
  },
  {
    name: "Guadeloupe",
    native: "Guadeloupe",
    phone: "590",
    continent: "NA",
    capital: "Basse-Terre",
    currency: "EUR",
    languages: ["fr"],
    code: "GP",
    code3: "GLP",
    emoji: "🇬🇵",
    emojiU: "U+1F1EC U+1F1F5",
  },
  {
    name: "Equatorial Guinea",
    native: "Guinea Ecuatorial",
    phone: "240",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "Malabo",
    currency: "XAF",
    languages: ["es", "fr"],
    code: "GQ",
    code3: "GNQ",
    emoji: "🇬🇶",
    emojiU: "U+1F1EC U+1F1F6",
  },
  {
    name: "Greece",
    native: "Ελλάδα",
    phone: "30",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Athens",
    currency: "EUR",
    languages: ["el"],
    code: "GR",
    code3: "GRC",
    emoji: "🇬🇷",
    emojiU: "U+1F1EC U+1F1F7",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    native: "South Georgia",
    phone: "500",
    continent: { code: "SA", region: "South America" },
    capital: "King Edward Point",
    currency: "GBP",
    languages: ["en"],
    code: "GS",
    code3: "SGS",
    emoji: "🇬🇸",
    emojiU: "U+1F1EC U+1F1F8",
  },
  {
    name: "Guatemala",
    native: "Guatemala",
    phone: "502",
    continent: "NA",
    capital: "Guatemala City",
    currency: "GTQ",
    languages: ["es"],
    code: "GT",
    code3: "GTM",
    emoji: "🇬🇹",
    emojiU: "U+1F1EC U+1F1F9",
  },
  {
    name: "Guam",
    native: "Guam",
    phone: "1671",
    continent: { code: "OC", region: "Oceania" },
    capital: "Hagåtña",
    currency: "USD",
    languages: ["en", "ch", "es"],
    code: "GU",
    code3: "GUM",
    emoji: "🇬🇺",
    emojiU: "U+1F1EC U+1F1FA",
  },
  {
    name: "Guinea-Bissau",
    native: "Guiné-Bissau",
    phone: "245",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Bissau",
    currency: "XOF",
    languages: ["pt"],
    code: "GW",
    code3: "GNB",
    emoji: "🇬🇼",
    emojiU: "U+1F1EC U+1F1FC",
  },
  {
    name: "Guyana",
    native: "Guyana",
    phone: "592",
    continent: { code: "SA", region: "South America" },
    capital: "Georgetown",
    currency: "GYD",
    languages: ["en"],
    code: "GY",
    code3: "GUY",
    emoji: "🇬🇾",
    emojiU: "U+1F1EC U+1F1FE",
  },
  {
    name: "Hong Kong",
    native: "香港",
    phone: "852",
    continent: { code: "AS", region: "Eastern Asia" },
    capital: "City of Victoria",
    currency: "HKD",
    languages: ["zh", "en"],
    code: "HK",
    code3: "HKG",
    emoji: "🇭🇰",
    emojiU: "U+1F1ED U+1F1F0",
  },
  {
    name: "Heard Island and McDonald Islands",
    native: "Heard Island and McDonald Islands",
    phone: "61",
    continent: { code: "AN", region: "Antarctica" },
    capital: "",
    currency: "AUD",
    languages: ["en"],
    code: "HM",
    code3: "HMD",
    emoji: "🇭🇲",
    emojiU: "U+1F1ED U+1F1F2",
  },
  {
    name: "Honduras",
    native: "Honduras",
    phone: "504",
    continent: "NA",
    capital: "Tegucigalpa",
    currency: "HNL",
    languages: ["es"],
    code: "HN",
    code3: "HND",
    emoji: "🇭🇳",
    emojiU: "U+1F1ED U+1F1F3",
  },
  {
    name: "Croatia",
    native: "Hrvatska",
    phone: "385",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Zagreb",
    currency: "HRK",
    languages: ["hr"],
    code: "HR",
    code3: "HRV",
    emoji: "🇭🇷",
    emojiU: "U+1F1ED U+1F1F7",
  },
  {
    name: "Haiti",
    native: "Haïti",
    phone: "509",
    continent: "NA",
    capital: "Port-au-Prince",
    currency: "HTG,USD",
    languages: ["fr", "ht"],
    code: "HT",
    code3: "HTI",
    emoji: "🇭🇹",
    emojiU: "U+1F1ED U+1F1F9",
  },
  {
    name: "Hungary",
    native: "Magyarország",
    phone: "36",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Budapest",
    currency: "HUF",
    languages: ["hu"],
    code: "HU",
    code3: "HUN",
    emoji: "🇭🇺",
    emojiU: "U+1F1ED U+1F1FA",
  },
  {
    name: "Indonesia",
    native: "Indonesia",
    phone: "62",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Jakarta",
    currency: "IDR",
    languages: ["id"],
    code: "ID",
    code3: "IDN",
    emoji: "🇮🇩",
    emojiU: "U+1F1EE U+1F1E9",
  },
  {
    name: "Ireland",
    native: "Éire",
    phone: "353",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Dublin",
    currency: "EUR",
    languages: ["ga", "en"],
    code: "IE",
    code3: "IRL",
    emoji: "🇮🇪",
    emojiU: "U+1F1EE U+1F1EA",
  },
  {
    name: "Israel",
    native: "יִשְׂרָאֵל",
    phone: "972",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Jerusalem",
    currency: "ILS",
    languages: ["he", "ar"],
    code: "IL",
    code3: "ISR",
    emoji: "🇮🇱",
    emojiU: "U+1F1EE U+1F1F1",
  },
  {
    name: "Isle of Man",
    native: "Isle of Man",
    phone: "44",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Douglas",
    currency: "GBP",
    languages: ["en", "gv"],
    code: "IM",
    code3: "IMN",
    emoji: "🇮🇲",
    emojiU: "U+1F1EE U+1F1F2",
  },
  {
    name: "India",
    native: "भारत",
    phone: "91",
    continent: { code: "AS", region: "Southern Asia" },
    capital: "New Delhi",
    currency: "INR",
    languages: ["hi", "en"],
    code: "IN",
    code3: "IND",
    emoji: "🇮🇳",
    emojiU: "U+1F1EE U+1F1F3",
  },
  {
    name: "British Indian Ocean Territory",
    native: "British Indian Ocean Territory",
    phone: "246",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Diego Garcia",
    currency: "USD",
    languages: ["en"],
    code: "IO",
    code3: "IOT",
    emoji: "🇮🇴",
    emojiU: "U+1F1EE U+1F1F4",
  },
  {
    name: "Iraq",
    native: "العراق",
    phone: "964",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Baghdad",
    currency: "IQD",
    languages: ["ar", "ku"],
    code: "IQ",
    code3: "IRQ",
    emoji: "🇮🇶",
    emojiU: "U+1F1EE U+1F1F6",
  },
  {
    name: "Iran",
    native: "ایران",
    phone: "98",
    continent: { code: "AS", region: "Southern Asia" },
    capital: "Tehran",
    currency: "IRR",
    languages: ["fa"],
    code: "IR",
    code3: "IRN",
    emoji: "🇮🇷",
    emojiU: "U+1F1EE U+1F1F7",
  },
  {
    name: "Iceland",
    native: "Ísland",
    phone: "354",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Reykjavik",
    currency: "ISK",
    languages: ["is"],
    code: "IS",
    code3: "ISL",
    emoji: "🇮🇸",
    emojiU: "U+1F1EE U+1F1F8",
  },
  {
    name: "Italy",
    native: "Italia",
    phone: "39",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Rome",
    currency: "EUR",
    languages: ["it"],
    code: "IT",
    code3: "ITA",
    emoji: "🇮🇹",
    emojiU: "U+1F1EE U+1F1F9",
  },
  {
    name: "Jersey",
    native: "Jersey",
    phone: "44",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Saint Helier",
    currency: "GBP",
    languages: ["en", "fr"],
    code: "JE",
    code3: "JEY",
    emoji: "🇯🇪",
    emojiU: "U+1F1EF U+1F1EA",
  },
  {
    name: "Jamaica",
    native: "Jamaica",
    phone: "1876",
    continent: "NA",
    capital: "Kingston",
    currency: "JMD",
    languages: ["en"],
    code: "JM",
    code3: "JAM",
    emoji: "🇯🇲",
    emojiU: "U+1F1EF U+1F1F2",
  },
  {
    name: "Jordan",
    native: "الأردن",
    phone: "962",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Amman",
    currency: "JOD",
    languages: ["ar"],
    code: "JO",
    code3: "JOR",
    emoji: "🇯🇴",
    emojiU: "U+1F1EF U+1F1F4",
  },
  {
    name: "Japan",
    native: "日本",
    phone: "81",
    continent: { code: "AS", region: "Eastern Asia" },
    capital: "Tokyo",
    currency: "JPY",
    languages: ["ja"],
    code: "JP",
    code3: "JPN",
    emoji: "🇯🇵",
    emojiU: "U+1F1EF U+1F1F5",
  },
  {
    name: "Kenya",
    native: "Kenya",
    phone: "254",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Nairobi",
    currency: "KES",
    languages: ["en", "sw"],
    code: "KE",
    code3: "KEN",
    emoji: "🇰🇪",
    emojiU: "U+1F1F0 U+1F1EA",
  },
  {
    name: "Kyrgyzstan",
    native: "Кыргызстан",
    phone: "996",
    continent: { code: "AS", region: "Central Asia" },
    capital: "Bishkek",
    currency: "KGS",
    languages: ["ky", "ru"],
    code: "KG",
    code3: "KGZ",
    emoji: "🇰🇬",
    emojiU: "U+1F1F0 U+1F1EC",
  },
  {
    name: "Cambodia",
    native: "Kâmpŭchéa",
    phone: "855",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Phnom Penh",
    currency: "KHR",
    languages: ["km"],
    code: "KH",
    code3: "KHM",
    emoji: "🇰🇭",
    emojiU: "U+1F1F0 U+1F1ED",
  },
  {
    name: "Kiribati",
    native: "Kiribati",
    phone: "686",
    continent: { code: "OC", region: "Oceania" },
    capital: "South Tarawa",
    currency: "AUD",
    languages: ["en"],
    code: "KI",
    code3: "KIR",
    emoji: "🇰🇮",
    emojiU: "U+1F1F0 U+1F1EE",
  },
  {
    name: "Comoros",
    native: "Komori",
    phone: "269",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Moroni",
    currency: "KMF",
    languages: ["ar", "fr"],
    code: "KM",
    code3: "COM",
    emoji: "🇰🇲",
    emojiU: "U+1F1F0 U+1F1F2",
  },
  {
    name: "Saint Kitts and Nevis",
    native: "Saint Kitts and Nevis",
    phone: "1869",
    continent: "NA",
    capital: "Basseterre",
    currency: "XCD",
    languages: ["en"],
    code: "KN",
    code3: "KNA",
    emoji: "🇰🇳",
    emojiU: "U+1F1F0 U+1F1F3",
  },
  {
    name: "North Korea",
    native: "북한",
    phone: "850",
    continent: { code: "AS", region: "Eastern Asia" },
    capital: "Pyongyang",
    currency: "KPW",
    languages: ["ko"],
    code: "KP",
    code3: "PRK",
    emoji: "🇰🇵",
    emojiU: "U+1F1F0 U+1F1F5",
  },
  {
    name: "South Korea",
    native: "대한민국",
    phone: "82",
    continent: { code: "AS", region: "Eastern Asia" },
    capital: "Seoul",
    currency: "KRW",
    languages: ["ko"],
    code: "KR",
    code3: "KOR",
    emoji: "🇰🇷",
    emojiU: "U+1F1F0 U+1F1F7",
  },
  {
    name: "Kuwait",
    native: "الكويت",
    phone: "965",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Kuwait City",
    currency: "KWD",
    languages: ["ar"],
    code: "KW",
    code3: "KWT",
    emoji: "🇰🇼",
    emojiU: "U+1F1F0 U+1F1FC",
  },
  {
    name: "Cayman Islands",
    native: "Cayman Islands",
    phone: "1345",
    continent: "NA",
    capital: "George Town",
    currency: "KYD",
    languages: ["en"],
    code: "KY",
    code3: "CYM",
    emoji: "🇰🇾",
    emojiU: "U+1F1F0 U+1F1FE",
  },
  {
    name: "Kazakhstan",
    native: "Қазақстан",
    phone: "76,77",
    continent: { code: "AS", region: "Central Asia" },
    capital: "Astana",
    currency: "KZT",
    languages: ["kk", "ru"],
    code: "KZ",
    code3: "KAZ",
    emoji: "🇰🇿",
    emojiU: "U+1F1F0 U+1F1FF",
  },
  {
    name: "Laos",
    native: "ສປປລາວ",
    phone: "856",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Vientiane",
    currency: "LAK",
    languages: ["lo"],
    code: "LA",
    code3: "LAO",
    emoji: "🇱🇦",
    emojiU: "U+1F1F1 U+1F1E6",
  },
  {
    name: "Lebanon",
    native: "لبنان",
    phone: "961",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Beirut",
    currency: "LBP",
    languages: ["ar", "fr"],
    code: "LB",
    code3: "LBN",
    emoji: "🇱🇧",
    emojiU: "U+1F1F1 U+1F1E7",
  },
  {
    name: "Saint Lucia",
    native: "Saint Lucia",
    phone: "1758",
    continent: "NA",
    capital: "Castries",
    currency: "XCD",
    languages: ["en"],
    code: "LC",
    code3: "LCA",
    emoji: "🇱🇨",
    emojiU: "U+1F1F1 U+1F1E8",
  },
  {
    name: "Liechtenstein",
    native: "Liechtenstein",
    phone: "423",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Vaduz",
    currency: "CHF",
    languages: ["de"],
    code: "LI",
    code3: "LIE",
    emoji: "🇱🇮",
    emojiU: "U+1F1F1 U+1F1EE",
  },
  {
    name: "Sri Lanka",
    native: "śrī laṃkāva",
    phone: "94",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Colombo",
    currency: "LKR",
    languages: ["si", "ta"],
    code: "LK",
    code3: "LKA",
    emoji: "🇱🇰",
    emojiU: "U+1F1F1 U+1F1F0",
  },
  {
    name: "Liberia",
    native: "Liberia",
    phone: "231",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Monrovia",
    currency: "LRD",
    languages: ["en"],
    code: "LR",
    code3: "LBR",
    emoji: "🇱🇷",
    emojiU: "U+1F1F1 U+1F1F7",
  },
  {
    name: "Lesotho",
    native: "Lesotho",
    phone: "266",
    continent: { code: "AF", region: "Southern Africa" },
    capital: "Maseru",
    currency: "LSL,ZAR",
    languages: ["en", "st"],
    code: "LS",
    code3: "LSO",
    emoji: "🇱🇸",
    emojiU: "U+1F1F1 U+1F1F8",
  },
  {
    name: "Lithuania",
    native: "Lietuva",
    phone: "370",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Vilnius",
    currency: "EUR",
    languages: ["lt"],
    code: "LT",
    code3: "LTU",
    emoji: "🇱🇹",
    emojiU: "U+1F1F1 U+1F1F9",
  },
  {
    name: "Luxembourg",
    native: "Luxembourg",
    phone: "352",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Luxembourg",
    currency: "EUR",
    languages: ["fr", "de", "lb"],
    code: "LU",
    code3: "LUX",
    emoji: "🇱🇺",
    emojiU: "U+1F1F1 U+1F1FA",
  },
  {
    name: "Latvia",
    native: "Latvija",
    phone: "371",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Riga",
    currency: "EUR",
    languages: ["lv"],
    code: "LV",
    code3: "LVA",
    emoji: "🇱🇻",
    emojiU: "U+1F1F1 U+1F1FB",
  },
  {
    name: "Libya",
    native: "‏ليبيا",
    phone: "218",
    continent: { code: "AF", region: "Northern Africa" },
    capital: "Tripoli",
    currency: "LYD",
    languages: ["ar"],
    code: "LY",
    code3: "LBY",
    emoji: "🇱🇾",
    emojiU: "U+1F1F1 U+1F1FE",
  },
  {
    name: "Morocco",
    native: "المغرب",
    phone: "212",
    continent: { code: "AF", region: "Northern Africa" },
    capital: "Rabat",
    currency: "MAD",
    languages: ["ar"],
    code: "MA",
    code3: "MAR",
    emoji: "🇲🇦",
    emojiU: "U+1F1F2 U+1F1E6",
  },
  {
    name: "Monaco",
    native: "Monaco",
    phone: "377",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Monaco",
    currency: "EUR",
    languages: ["fr"],
    code: "MC",
    code3: "MCO",
    emoji: "🇲🇨",
    emojiU: "U+1F1F2 U+1F1E8",
  },
  {
    name: "Moldova",
    native: "Moldova",
    phone: "373",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Chișinău",
    currency: "MDL",
    languages: ["ro"],
    code: "MD",
    code3: "MDA",
    emoji: "🇲🇩",
    emojiU: "U+1F1F2 U+1F1E9",
  },
  {
    name: "Montenegro",
    native: "Црна Гора",
    phone: "382",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Podgorica",
    currency: "EUR",
    languages: ["sr", "bs", "sq", "hr"],
    code: "ME",
    code3: "MNE",
    emoji: "🇲🇪",
    emojiU: "U+1F1F2 U+1F1EA",
  },
  {
    name: "Saint Martin",
    native: "Saint-Martin",
    phone: "590",
    continent: "NA",
    capital: "Marigot",
    currency: "EUR",
    languages: ["en", "fr", "nl"],
    code: "MF",
    code3: "MAF",
    emoji: "🇲🇫",
    emojiU: "U+1F1F2 U+1F1EB",
  },
  {
    name: "Madagascar",
    native: "Madagasikara",
    phone: "261",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Antananarivo",
    currency: "MGA",
    languages: ["fr", "mg"],
    code: "MG",
    code3: "MDG",
    emoji: "🇲🇬",
    emojiU: "U+1F1F2 U+1F1EC",
  },
  {
    name: "Marshall Islands",
    native: "M̧ajeļ",
    phone: "692",
    continent: { code: "OC", region: "Oceania" },
    capital: "Majuro",
    currency: "USD",
    languages: ["en", "mh"],
    code: "MH",
    code3: "MHL",
    emoji: "🇲🇭",
    emojiU: "U+1F1F2 U+1F1ED",
  },
  {
    name: "North Macedonia",
    native: "Северна Македонија",
    phone: "389",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Skopje",
    currency: "MKD",
    languages: ["mk"],
    code: "MK",
    code3: "MKD",
    emoji: "🇲🇰",
    emojiU: "U+1F1F2 U+1F1F0",
  },
  {
    name: "Mali",
    native: "Mali",
    phone: "223",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Bamako",
    currency: "XOF",
    languages: ["fr"],
    code: "ML",
    code3: "MLI",
    emoji: "🇲🇱",
    emojiU: "U+1F1F2 U+1F1F1",
  },
  {
    name: "Myanmar [Burma]",
    native: "မြန်မာ",
    phone: "95",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Naypyidaw",
    currency: "MMK",
    languages: ["my"],
    code: "MM",
    code3: "MMR",
    emoji: "🇲🇲",
    emojiU: "U+1F1F2 U+1F1F2",
  },
  {
    name: "Mongolia",
    native: "Монгол улс",
    phone: "976",
    continent: { code: "AS", region: "Eastern Asia" },
    capital: "Ulan Bator",
    currency: "MNT",
    languages: ["mn"],
    code: "MN",
    code3: "MNG",
    emoji: "🇲🇳",
    emojiU: "U+1F1F2 U+1F1F3",
  },
  {
    name: "Macao",
    native: "澳門",
    phone: "853",
    continent: { code: "AS", region: "Eastern Asia" },
    capital: "",
    currency: "MOP",
    languages: ["zh", "pt"],
    code: "MO",
    code3: "MAC",
    emoji: "🇲🇴",
    emojiU: "U+1F1F2 U+1F1F4",
  },
  {
    name: "Northern Mariana Islands",
    native: "Northern Mariana Islands",
    phone: "1670",
    continent: { code: "OC", region: "Oceania" },
    capital: "Saipan",
    currency: "USD",
    languages: ["en", "ch"],
    code: "MP",
    code3: "MNP",
    emoji: "🇲🇵",
    emojiU: "U+1F1F2 U+1F1F5",
  },
  {
    name: "Martinique",
    native: "Martinique",
    phone: "596",
    continent: "NA",
    capital: "Fort-de-France",
    currency: "EUR",
    languages: ["fr"],
    code: "MQ",
    code3: "MTQ",
    emoji: "🇲🇶",
    emojiU: "U+1F1F2 U+1F1F6",
  },
  {
    name: "Mauritania",
    native: "موريتانيا",
    phone: "222",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Nouakchott",
    currency: "MRU",
    languages: ["ar"],
    code: "MR",
    code3: "MRT",
    emoji: "🇲🇷",
    emojiU: "U+1F1F2 U+1F1F7",
  },
  {
    name: "Montserrat",
    native: "Montserrat",
    phone: "1664",
    continent: "NA",
    capital: "Plymouth",
    currency: "XCD",
    languages: ["en"],
    code: "MS",
    code3: "MSR",
    emoji: "🇲🇸",
    emojiU: "U+1F1F2 U+1F1F8",
  },
  {
    name: "Malta",
    native: "Malta",
    phone: "356",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Valletta",
    currency: "EUR",
    languages: ["mt", "en"],
    code: "MT",
    code3: "MLT",
    emoji: "🇲🇹",
    emojiU: "U+1F1F2 U+1F1F9",
  },
  {
    name: "Mauritius",
    native: "Maurice",
    phone: "230",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Port Louis",
    currency: "MUR",
    languages: ["en"],
    code: "MU",
    code3: "MUS",
    emoji: "🇲🇺",
    emojiU: "U+1F1F2 U+1F1FA",
  },
  {
    name: "Maldives",
    native: "Maldives",
    phone: "960",
    continent: { code: "AS", region: "Southern Asia" },
    capital: "Malé",
    currency: "MVR",
    languages: ["dv"],
    code: "MV",
    code3: "MDV",
    emoji: "🇲🇻",
    emojiU: "U+1F1F2 U+1F1FB",
  },
  {
    name: "Malawi",
    native: "Malawi",
    phone: "265",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Lilongwe",
    currency: "MWK",
    languages: ["en", "ny"],
    code: "MW",
    code3: "MWI",
    emoji: "🇲🇼",
    emojiU: "U+1F1F2 U+1F1FC",
  },
  {
    name: "Mexico",
    native: "México",
    phone: "52",
    continent: "NA",
    capital: "Mexico City",
    currency: "MXN",
    languages: ["es"],
    code: "MX",
    code3: "MEX",
    emoji: "🇲🇽",
    emojiU: "U+1F1F2 U+1F1FD",
  },
  {
    name: "Malaysia",
    native: "Malaysia",
    phone: "60",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Kuala Lumpur",
    currency: "MYR",
    languages: ["ms"],
    code: "MY",
    code3: "MYS",
    emoji: "🇲🇾",
    emojiU: "U+1F1F2 U+1F1FE",
  },
  {
    name: "Mozambique",
    native: "Moçambique",
    phone: "258",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Maputo",
    currency: "MZN",
    languages: ["pt"],
    code: "MZ",
    code3: "MOZ",
    emoji: "🇲🇿",
    emojiU: "U+1F1F2 U+1F1FF",
  },
  {
    name: "Namibia",
    native: "Namibia",
    phone: "264",
    continent: { code: "AF", region: "Southern Africa" },
    capital: "Windhoek",
    currency: "NAD,ZAR",
    languages: ["en", "af"],
    code: "NA",
    code3: "NAM",
    emoji: "🇳🇦",
    emojiU: "U+1F1F3 U+1F1E6",
  },
  {
    name: "New Caledonia",
    native: "Nouvelle-Calédonie",
    phone: "687",
    continent: { code: "OC", region: "Oceania" },
    capital: "Nouméa",
    currency: "XPF",
    languages: ["fr"],
    code: "NC",
    code3: "NCL",
    emoji: "🇳🇨",
    emojiU: "U+1F1F3 U+1F1E8",
  },
  {
    name: "Niger",
    native: "Niger",
    phone: "227",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Niamey",
    currency: "XOF",
    languages: ["fr"],
    code: "NE",
    code3: "NER",
    emoji: "🇳🇪",
    emojiU: "U+1F1F3 U+1F1EA",
  },
  {
    name: "Norfolk Island",
    native: "Norfolk Island",
    phone: "672",
    continent: { code: "OC", region: "Oceania" },
    capital: "Kingston",
    currency: "AUD",
    languages: ["en"],
    code: "NF",
    code3: "NFK",
    emoji: "🇳🇫",
    emojiU: "U+1F1F3 U+1F1EB",
  },
  {
    name: "Nigeria",
    native: "Nigeria",
    phone: "234",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Abuja",
    currency: "NGN",
    languages: ["en"],
    code: "NG",
    code3: "NGA",
    emoji: "🇳🇬",
    emojiU: "U+1F1F3 U+1F1EC",
  },
  {
    name: "Nicaragua",
    native: "Nicaragua",
    phone: "505",
    continent: "NA",
    capital: "Managua",
    currency: "NIO",
    languages: ["es"],
    code: "NI",
    code3: "NIC",
    emoji: "🇳🇮",
    emojiU: "U+1F1F3 U+1F1EE",
  },
  {
    name: "Netherlands",
    native: "Nederland",
    phone: "31",
    continent: { code: "EU", region: "Western Europe" },
    capital: "Amsterdam",
    currency: "EUR",
    languages: ["nl"],
    code: "NL",
    code3: "NLD",
    emoji: "🇳🇱",
    emojiU: "U+1F1F3 U+1F1F1",
  },
  {
    name: "Norway",
    native: "Norge",
    phone: "47",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Oslo",
    currency: "NOK",
    languages: ["no", "nb", "nn"],
    code: "NO",
    code3: "NOR",
    emoji: "🇳🇴",
    emojiU: "U+1F1F3 U+1F1F4",
  },
  {
    name: "Nepal",
    native: "नपल",
    phone: "977",
    continent: { code: "AS", region: "Southern Asia" },
    capital: "Kathmandu",
    currency: "NPR",
    languages: ["ne"],
    code: "NP",
    code3: "NPL",
    emoji: "🇳🇵",
    emojiU: "U+1F1F3 U+1F1F5",
  },
  {
    name: "Nauru",
    native: "Nauru",
    phone: "674",
    continent: { code: "OC", region: "Oceania" },
    capital: "Yaren",
    currency: "AUD",
    languages: ["en", "na"],
    code: "NR",
    code3: "NRU",
    emoji: "🇳🇷",
    emojiU: "U+1F1F3 U+1F1F7",
  },
  {
    name: "Niue",
    native: "Niuē",
    phone: "683",
    continent: { code: "OC", region: "Oceania" },
    capital: "Alofi",
    currency: "NZD",
    languages: ["en"],
    code: "NU",
    code3: "NIU",
    emoji: "🇳🇺",
    emojiU: "U+1F1F3 U+1F1FA",
  },
  {
    name: "New Zealand",
    native: "New Zealand",
    phone: "64",
    continent: { code: "OC", region: "Oceania" },
    capital: "Wellington",
    currency: "NZD",
    languages: ["en", "mi"],
    code: "NZ",
    code3: "NZL",
    emoji: "🇳🇿",
    emojiU: "U+1F1F3 U+1F1FF",
  },
  {
    name: "Oman",
    native: "عمان",
    phone: "968",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Muscat",
    currency: "OMR",
    languages: ["ar"],
    code: "OM",
    code3: "OMN",
    emoji: "🇴🇲",
    emojiU: "U+1F1F4 U+1F1F2",
  },
  {
    name: "Panama",
    native: "Panamá",
    phone: "507",
    continent: "NA",
    capital: "Panama City",
    currency: "PAB,USD",
    languages: ["es"],
    code: "PA",
    code3: "PAN",
    emoji: "🇵🇦",
    emojiU: "U+1F1F5 U+1F1E6",
  },
  {
    name: "Peru",
    native: "Perú",
    phone: "51",
    continent: { code: "SA", region: "South America" },
    capital: "Lima",
    currency: "PEN",
    languages: ["es"],
    code: "PE",
    code3: "PER",
    emoji: "🇵🇪",
    emojiU: "U+1F1F5 U+1F1EA",
  },
  {
    name: "French Polynesia",
    native: "Polynésie française",
    phone: "689",
    continent: { code: "OC", region: "Oceania" },
    capital: "Papeetē",
    currency: "XPF",
    languages: ["fr"],
    code: "PF",
    code3: "PYF",
    emoji: "🇵🇫",
    emojiU: "U+1F1F5 U+1F1EB",
  },
  {
    name: "Papua New Guinea",
    native: "Papua Niugini",
    phone: "675",
    continent: { code: "OC", region: "Oceania" },
    capital: "Port Moresby",
    currency: "PGK",
    languages: ["en"],
    code: "PG",
    code3: "PNG",
    emoji: "🇵🇬",
    emojiU: "U+1F1F5 U+1F1EC",
  },
  {
    name: "Philippines",
    native: "Pilipinas",
    phone: "63",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Manila",
    currency: "PHP",
    languages: ["en"],
    code: "PH",
    code3: "PHL",
    emoji: "🇵🇭",
    emojiU: "U+1F1F5 U+1F1ED",
  },
  {
    name: "Pakistan",
    native: "Pakistan",
    phone: "92",
    continent: { code: "AS", region: "Southern Asia" },
    capital: "Islamabad",
    currency: "PKR",
    languages: ["en", "ur"],
    code: "PK",
    code3: "PAK",
    emoji: "🇵🇰",
    emojiU: "U+1F1F5 U+1F1F0",
  },
  {
    name: "Poland",
    native: "Polska",
    phone: "48",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Warsaw",
    currency: "PLN",
    languages: ["pl"],
    code: "PL",
    code3: "POL",
    emoji: "🇵🇱",
    emojiU: "U+1F1F5 U+1F1F1",
  },
  {
    name: "Saint Pierre and Miquelon",
    native: "Saint-Pierre-et-Miquelon",
    phone: "508",
    continent: "NA",
    capital: "Saint-Pierre",
    currency: "EUR",
    languages: ["fr"],
    code: "PM",
    code3: "SPM",
    emoji: "🇵🇲",
    emojiU: "U+1F1F5 U+1F1F2",
  },
  {
    name: "Pitcairn Islands",
    native: "Pitcairn Islands",
    phone: "64",
    continent: { code: "OC", region: "Oceania" },
    capital: "Adamstown",
    currency: "NZD",
    languages: ["en"],
    code: "PN",
    code3: "PCN",
    emoji: "🇵🇳",
    emojiU: "U+1F1F5 U+1F1F3",
  },
  {
    name: "Puerto Rico",
    native: "Puerto Rico",
    phone: "1787,1939",
    continent: "NA",
    capital: "San Juan",
    currency: "USD",
    languages: ["es", "en"],
    code: "PR",
    code3: "PRI",
    emoji: "🇵🇷",
    emojiU: "U+1F1F5 U+1F1F7",
  },
  {
    name: "Palestine",
    native: "فلسطين",
    phone: "970",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Ramallah",
    currency: "ILS",
    languages: ["ar"],
    code: "PS",
    code3: "PSE",
    emoji: "🇵🇸",
    emojiU: "U+1F1F5 U+1F1F8",
  },
  {
    name: "Portugal",
    native: "Portugal",
    phone: "351",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Lisbon",
    currency: "EUR",
    languages: ["pt"],
    code: "PT",
    code3: "PRT",
    emoji: "🇵🇹",
    emojiU: "U+1F1F5 U+1F1F9",
  },
  {
    name: "Palau",
    native: "Palau",
    phone: "680",
    continent: { code: "OC", region: "Oceania" },
    capital: "Ngerulmud",
    currency: "USD",
    languages: ["en"],
    code: "PW",
    code3: "PLW",
    emoji: "🇵🇼",
    emojiU: "U+1F1F5 U+1F1FC",
  },
  {
    name: "Paraguay",
    native: "Paraguay",
    phone: "595",
    continent: { code: "SA", region: "South America" },
    capital: "Asunción",
    currency: "PYG",
    languages: ["es", "gn"],
    code: "PY",
    code3: "PRY",
    emoji: "🇵🇾",
    emojiU: "U+1F1F5 U+1F1FE",
  },
  {
    name: "Qatar",
    native: "قطر",
    phone: "974",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Doha",
    currency: "QAR",
    languages: ["ar"],
    code: "QA",
    code3: "QAT",
    emoji: "🇶🇦",
    emojiU: "U+1F1F6 U+1F1E6",
  },
  {
    name: "Réunion",
    native: "La Réunion",
    phone: "262",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Saint-Denis",
    currency: "EUR",
    languages: ["fr"],
    code: "RE",
    code3: "REU",
    emoji: "🇷🇪",
    emojiU: "U+1F1F7 U+1F1EA",
  },
  {
    name: "Romania",
    native: "România",
    phone: "40",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Bucharest",
    currency: "RON",
    languages: ["ro"],
    code: "RO",
    code3: "ROM",
    emoji: "🇷🇴",
    emojiU: "U+1F1F7 U+1F1F4",
  },
  {
    name: "Serbia",
    native: "Србија",
    phone: "381",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Belgrade",
    currency: "RSD",
    languages: ["sr"],
    code: "RS",
    code3: "SRB",
    emoji: "🇷🇸",
    emojiU: "U+1F1F7 U+1F1F8",
  },
  {
    name: "Russia",
    native: "Россия",
    phone: "7",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Moscow",
    currency: "RUB",
    languages: ["ru"],
    code: "RU",
    code3: "RUS",
    emoji: "🇷🇺",
    emojiU: "U+1F1F7 U+1F1FA",
  },
  {
    name: "Rwanda",
    native: "Rwanda",
    phone: "250",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Kigali",
    currency: "RWF",
    languages: ["rw", "en", "fr"],
    code: "RW",
    code3: "RWA",
    emoji: "🇷🇼",
    emojiU: "U+1F1F7 U+1F1FC",
  },
  {
    name: "Saudi Arabia",
    native: "العربية السعودية",
    phone: "966",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Riyadh",
    currency: "SAR",
    languages: ["ar"],
    code: "SA",
    code3: "SAU",
    emoji: "🇸🇦",
    emojiU: "U+1F1F8 U+1F1E6",
  },
  {
    name: "Solomon Islands",
    native: "Solomon Islands",
    phone: "677",
    continent: { code: "OC", region: "Oceania" },
    capital: "Honiara",
    currency: "SBD",
    languages: ["en"],
    code: "SB",
    code3: "SLB",
    emoji: "🇸🇧",
    emojiU: "U+1F1F8 U+1F1E7",
  },
  {
    name: "Seychelles",
    native: "Seychelles",
    phone: "248",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Victoria",
    currency: "SCR",
    languages: ["fr", "en"],
    code: "SC",
    code3: "SYC",
    emoji: "🇸🇨",
    emojiU: "U+1F1F8 U+1F1E8",
  },
  {
    name: "Sudan",
    native: "السودان",
    phone: "249",
    continent: { code: "AF", region: "Northern Africa" },
    capital: "Khartoum",
    currency: "SDG",
    languages: ["ar", "en"],
    code: "SD",
    code3: "SDN",
    emoji: "🇸🇩",
    emojiU: "U+1F1F8 U+1F1E9",
  },
  {
    name: "Sweden",
    native: "Sverige",
    phone: "46",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Stockholm",
    currency: "SEK",
    languages: ["sv"],
    code: "SE",
    code3: "SWE",
    emoji: "🇸🇪",
    emojiU: "U+1F1F8 U+1F1EA",
  },
  {
    name: "Singapore",
    native: "Singapore",
    phone: "65",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Singapore",
    currency: "SGD",
    languages: ["en", "ms", "ta", "zh"],
    code: "SG",
    code3: "SGP",
    emoji: "🇸🇬",
    emojiU: "U+1F1F8 U+1F1EC",
  },
  {
    name: "Saint Helena",
    native: "Saint Helena",
    phone: "290",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Jamestown",
    currency: "SHP",
    languages: ["en"],
    code: "SH",
    code3: "SHN",
    emoji: "🇸🇭",
    emojiU: "U+1F1F8 U+1F1ED",
  },
  {
    name: "Slovenia",
    native: "Slovenija",
    phone: "386",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Ljubljana",
    currency: "EUR",
    languages: ["sl"],
    code: "SI",
    code3: "SVN",
    emoji: "🇸🇮",
    emojiU: "U+1F1F8 U+1F1EE",
  },
  {
    name: "Svalbard and Jan Mayen",
    native: "Svalbard og Jan Mayen",
    phone: "4779",
    continent: { code: "EU", region: "Northern Europe" },
    capital: "Longyearbyen",
    currency: "NOK",
    languages: ["no"],
    code: "SJ",
    code3: "SJM",
    emoji: "🇸🇯",
    emojiU: "U+1F1F8 U+1F1EF",
  },
  {
    name: "Slovakia",
    native: "Slovensko",
    phone: "421",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Bratislava",
    currency: "EUR",
    languages: ["sk"],
    code: "SK",
    code3: "SVK",
    emoji: "🇸🇰",
    emojiU: "U+1F1F8 U+1F1F0",
  },
  {
    name: "Sierra Leone",
    native: "Sierra Leone",
    phone: "232",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Freetown",
    currency: "SLL",
    languages: ["en"],
    code: "SL",
    code3: "SLE",
    emoji: "🇸🇱",
    emojiU: "U+1F1F8 U+1F1F1",
  },
  {
    name: "San Marino",
    native: "San Marino",
    phone: "378",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "City of San Marino",
    currency: "EUR",
    languages: ["it"],
    code: "SM",
    code3: "SMR",
    emoji: "🇸🇲",
    emojiU: "U+1F1F8 U+1F1F2",
  },
  {
    name: "Senegal",
    native: "Sénégal",
    phone: "221",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Dakar",
    currency: "XOF",
    languages: ["fr"],
    code: "SN",
    code3: "SEN",
    emoji: "🇸🇳",
    emojiU: "U+1F1F8 U+1F1F3",
  },
  {
    name: "Somalia",
    native: "Soomaaliya",
    phone: "252",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Mogadishu",
    currency: "SOS",
    languages: ["so", "ar"],
    code: "SO",
    code3: "SOM",
    emoji: "🇸🇴",
    emojiU: "U+1F1F8 U+1F1F4",
  },
  {
    name: "Suriname",
    native: "Suriname",
    phone: "597",
    continent: { code: "SA", region: "South America" },
    capital: "Paramaribo",
    currency: "SRD",
    languages: ["nl"],
    code: "SR",
    code3: "SUR",
    emoji: "🇸🇷",
    emojiU: "U+1F1F8 U+1F1F7",
  },
  {
    name: "South Sudan",
    native: "South Sudan",
    phone: "211",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "Juba",
    currency: "SSP",
    languages: ["en"],
    code: "SS",
    code3: "SSD",
    emoji: "🇸🇸",
    emojiU: "U+1F1F8 U+1F1F8",
  },
  {
    name: "São Tomé and Príncipe",
    native: "São Tomé e Príncipe",
    phone: "239",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "São Tomé",
    currency: "STN",
    languages: ["pt"],
    code: "ST",
    code3: "STP",
    emoji: "🇸🇹",
    emojiU: "U+1F1F8 U+1F1F9",
  },
  {
    name: "El Salvador",
    native: "El Salvador",
    phone: "503",
    continent: "NA",
    capital: "San Salvador",
    currency: "SVC,USD",
    languages: ["es"],
    code: "SV",
    code3: "SLV",
    emoji: "🇸🇻",
    emojiU: "U+1F1F8 U+1F1FB",
  },
  {
    name: "Sint Maarten",
    native: "Sint Maarten",
    phone: "1721",
    continent: "NA",
    capital: "Philipsburg",
    currency: "ANG",
    languages: ["nl", "en"],
    code: "SX",
    code3: "SXM",
    emoji: "🇸🇽",
    emojiU: "U+1F1F8 U+1F1FD",
  },
  {
    name: "Syria",
    native: "سوريا",
    phone: "963",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Damascus",
    currency: "SYP",
    languages: ["ar"],
    code: "SY",
    code3: "SYR",
    emoji: "🇸🇾",
    emojiU: "U+1F1F8 U+1F1FE",
  },
  {
    name: "Swaziland",
    native: "Swaziland",
    phone: "268",
    continent: { code: "AF", region: "Southern Africa" },
    capital: "Lobamba",
    currency: "SZL",
    languages: ["en", "ss"],
    code: "SZ",
    code3: "SWZ",
    emoji: "🇸🇿",
    emojiU: "U+1F1F8 U+1F1FF",
  },
  {
    name: "Turks and Caicos Islands",
    native: "Turks and Caicos Islands",
    phone: "1649",
    continent: "NA",
    capital: "Cockburn Town",
    currency: "USD",
    languages: ["en"],
    code: "TC",
    code3: "TCA",
    emoji: "🇹🇨",
    emojiU: "U+1F1F9 U+1F1E8",
  },
  {
    name: "Chad",
    native: "Tchad",
    phone: "235",
    continent: { code: "AF", region: "Middle Africa" },
    capital: "N'Djamena",
    currency: "XAF",
    languages: ["fr", "ar"],
    code: "TD",
    code3: "TCD",
    emoji: "🇹🇩",
    emojiU: "U+1F1F9 U+1F1E9",
  },
  {
    name: "French Southern Territories",
    native: "Territoire des Terres australes et antarctiques fr",
    phone: "262",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Port-aux-Français",
    currency: "EUR",
    languages: ["fr"],
    code: "TF",
    code3: "ATF",
    emoji: "🇹🇫",
    emojiU: "U+1F1F9 U+1F1EB",
  },
  {
    name: "Togo",
    native: "Togo",
    phone: "228",
    continent: { code: "AF", region: "Western Africa" },
    capital: "Lomé",
    currency: "XOF",
    languages: ["fr"],
    code: "TG",
    code3: "TGO",
    emoji: "🇹🇬",
    emojiU: "U+1F1F9 U+1F1EC",
  },
  {
    name: "Thailand",
    native: "ประเทศไทย",
    phone: "66",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Bangkok",
    currency: "THB",
    languages: ["th"],
    code: "TH",
    code3: "THA",
    emoji: "🇹🇭",
    emojiU: "U+1F1F9 U+1F1ED",
  },
  {
    name: "Tajikistan",
    native: "Тоҷикистон",
    phone: "992",
    continent: { code: "AS", region: "Central Asia" },
    capital: "Dushanbe",
    currency: "TJS",
    languages: ["tg", "ru"],
    code: "TJ",
    code3: "TJK",
    emoji: "🇹🇯",
    emojiU: "U+1F1F9 U+1F1EF",
  },
  {
    name: "Tokelau",
    native: "Tokelau",
    phone: "690",
    continent: { code: "OC", region: "Oceania" },
    capital: "Fakaofo",
    currency: "NZD",
    languages: ["en"],
    code: "TK",
    code3: "TKL",
    emoji: "🇹🇰",
    emojiU: "U+1F1F9 U+1F1F0",
  },
  {
    name: "East Timor",
    native: "Timor-Leste",
    phone: "670",
    continent: { code: "OC", region: "Oceania" },
    capital: "Dili",
    currency: "USD",
    languages: ["pt"],
    code: "TL",
    code3: "TLS",
    emoji: "🇹🇱",
    emojiU: "U+1F1F9 U+1F1F1",
  },
  {
    name: "Turkmenistan",
    native: "Türkmenistan",
    phone: "993",
    continent: { code: "AS", region: "Central Asia" },
    capital: "Ashgabat",
    currency: "TMT",
    languages: ["tk", "ru"],
    code: "TM",
    code3: "TKM",
    emoji: "🇹🇲",
    emojiU: "U+1F1F9 U+1F1F2",
  },
  {
    name: "Tunisia",
    native: "تونس",
    phone: "216",
    continent: { code: "AF", region: "Northern Africa" },
    capital: "Tunis",
    currency: "TND",
    languages: ["ar"],
    code: "TN",
    code3: "TUN",
    emoji: "🇹🇳",
    emojiU: "U+1F1F9 U+1F1F3",
  },
  {
    name: "Tonga",
    native: "Tonga",
    phone: "676",
    continent: { code: "OC", region: "Oceania" },
    capital: "Nuku'alofa",
    currency: "TOP",
    languages: ["en", "to"],
    code: "TO",
    code3: "TON",
    emoji: "🇹🇴",
    emojiU: "U+1F1F9 U+1F1F4",
  },
  {
    name: "Turkey",
    native: "Türkiye",
    phone: "90",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Ankara",
    currency: "TRY",
    languages: ["tr"],
    code: "TR",
    code3: "TUR",
    emoji: "🇹🇷",
    emojiU: "U+1F1F9 U+1F1F7",
  },
  {
    name: "Trinidad and Tobago",
    native: "Trinidad and Tobago",
    phone: "1868",
    continent: "NA",
    capital: "Port of Spain",
    currency: "TTD",
    languages: ["en"],
    code: "TT",
    code3: "TTO",
    emoji: "🇹🇹",
    emojiU: "U+1F1F9 U+1F1F9",
  },
  {
    name: "Tuvalu",
    native: "Tuvalu",
    phone: "688",
    continent: { code: "OC", region: "Oceania" },
    capital: "Funafuti",
    currency: "AUD",
    languages: ["en"],
    code: "TV",
    code3: "TUV",
    emoji: "🇹🇻",
    emojiU: "U+1F1F9 U+1F1FB",
  },
  {
    name: "Taiwan",
    native: "臺灣",
    phone: "886",
    continent: { code: "AS", region: "Eastern Asia" },
    capital: "Taipei",
    currency: "TWD",
    languages: ["zh"],
    code: "TW",
    code3: "TWN",
    emoji: "🇹🇼",
    emojiU: "U+1F1F9 U+1F1FC",
  },
  {
    name: "Tanzania",
    native: "Tanzania",
    phone: "255",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Dodoma",
    currency: "TZS",
    languages: ["sw", "en"],
    code: "TZ",
    code3: "TZA",
    emoji: "🇹🇿",
    emojiU: "U+1F1F9 U+1F1FF",
  },
  {
    name: "Ukraine",
    native: "Україна",
    phone: "380",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Kyiv",
    currency: "UAH",
    languages: ["uk"],
    code: "UA",
    code3: "UKR",
    emoji: "🇺🇦",
    emojiU: "U+1F1FA U+1F1E6",
  },
  {
    name: "Uganda",
    native: "Uganda",
    phone: "256",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Kampala",
    currency: "UGX",
    languages: ["en", "sw"],
    code: "UG",
    code3: "UGA",
    emoji: "🇺🇬",
    emojiU: "U+1F1FA U+1F1EC",
  },
  {
    name: "U.S. Minor Outlying Islands",
    native: "United States Minor Outlying Islands",
    phone: "1",
    continent: { code: "OC", region: "Oceania" },
    capital: "",
    currency: "USD",
    languages: ["en"],
    code: "UM",
    code3: "UMI",
    emoji: "🇺🇲",
    emojiU: "U+1F1FA U+1F1F2",
  },
  {
    name: "United States",
    native: "United States",
    phone: "1",
    continent: "NA",
    capital: "Washington D.C.",
    currency: "USD,USN,USS",
    languages: ["en"],
    code: "US",
    code3: "USA",
    emoji: "🇺🇸",
    emojiU: "U+1F1FA U+1F1F8",
  },
  {
    name: "Uruguay",
    native: "Uruguay",
    phone: "598",
    continent: { code: "SA", region: "South America" },
    capital: "Montevideo",
    currency: "UYI,UYU",
    languages: ["es"],
    code: "UY",
    code3: "URY",
    emoji: "🇺🇾",
    emojiU: "U+1F1FA U+1F1FE",
  },
  {
    name: "Uzbekistan",
    native: "O‘zbekiston",
    phone: "998",
    continent: { code: "AS", region: "Central Asia" },
    capital: "Tashkent",
    currency: "UZS",
    languages: ["uz", "ru"],
    code: "UZ",
    code3: "UZB",
    emoji: "🇺🇿",
    emojiU: "U+1F1FA U+1F1FF",
  },
  {
    name: "Vatican City",
    native: "Vaticano",
    phone: "379",
    continent: { code: "EU", region: "Southern Europe" },
    capital: "Vatican City",
    currency: "EUR",
    languages: ["it", "la"],
    code: "VA",
    code3: "VAT",
    emoji: "🇻🇦",
    emojiU: "U+1F1FB U+1F1E6",
  },
  {
    name: "Saint Vincent and the Grenadines",
    native: "Saint Vincent and the Grenadines",
    phone: "1784",
    continent: "NA",
    capital: "Kingstown",
    currency: "XCD",
    languages: ["en"],
    code: "VC",
    code3: "VCT",
    emoji: "🇻🇨",
    emojiU: "U+1F1FB U+1F1E8",
  },
  {
    name: "Venezuela",
    native: "Venezuela",
    phone: "58",
    continent: { code: "SA", region: "South America" },
    capital: "Caracas",
    currency: "VES",
    languages: ["es"],
    code: "VE",
    code3: "VEN",
    emoji: "🇻🇪",
    emojiU: "U+1F1FB U+1F1EA",
  },
  {
    name: "British Virgin Islands",
    native: "British Virgin Islands",
    phone: "1284",
    continent: "NA",
    capital: "Road Town",
    currency: "USD",
    languages: ["en"],
    code: "VG",
    code3: "VGB",
    emoji: "🇻🇬",
    emojiU: "U+1F1FB U+1F1EC",
  },
  {
    name: "U.S. Virgin Islands",
    native: "United States Virgin Islands",
    phone: "1340",
    continent: "NA",
    capital: "Charlotte Amalie",
    currency: "USD",
    languages: ["en"],
    code: "VI",
    code3: "VIR",
    emoji: "🇻🇮",
    emojiU: "U+1F1FB U+1F1EE",
  },
  {
    name: "Vietnam",
    native: "Việt Nam",
    phone: "84",
    continent: { code: "AS", region: "South-eastern Asia" },
    capital: "Hanoi",
    currency: "VND",
    languages: ["vi"],
    code: "VN",
    code3: "VNM",
    emoji: "🇻🇳",
    emojiU: "U+1F1FB U+1F1F3",
  },
  {
    name: "Vanuatu",
    native: "Vanuatu",
    phone: "678",
    continent: { code: "OC", region: "Oceania" },
    capital: "Port Vila",
    currency: "VUV",
    languages: ["bi", "en", "fr"],
    code: "VU",
    code3: "VUT",
    emoji: "🇻🇺",
    emojiU: "U+1F1FB U+1F1FA",
  },
  {
    name: "Wallis and Futuna",
    native: "Wallis et Futuna",
    phone: "681",
    continent: { code: "OC", region: "Oceania" },
    capital: "Mata-Utu",
    currency: "XPF",
    languages: ["fr"],
    code: "WF",
    code3: "WLF",
    emoji: "🇼🇫",
    emojiU: "U+1F1FC U+1F1EB",
  },
  {
    name: "Samoa",
    native: "Samoa",
    phone: "685",
    continent: { code: "OC", region: "Oceania" },
    capital: "Apia",
    currency: "WST",
    languages: ["sm", "en"],
    code: "WS",
    code3: "WSM",
    emoji: "🇼🇸",
    emojiU: "U+1F1FC U+1F1F8",
  },
  {
    name: "Kosovo",
    native: "Republika e Kosovës",
    phone: "377,381,383,386",
    continent: { code: "EU", region: "Eastern Europe" },
    capital: "Pristina",
    currency: "EUR",
    languages: ["sq", "sr"],
    code: "XK",
    code3: "XKX",
    emoji: "🇽🇰",
    emojiU: "U+1F1FD U+1F1F0",
  },
  {
    name: "Yemen",
    native: "اليَمَن",
    phone: "967",
    continent: { code: "AS", region: "Western Asia" },
    capital: "Sana'a",
    currency: "YER",
    languages: ["ar"],
    code: "YE",
    code3: "YEM",
    emoji: "🇾🇪",
    emojiU: "U+1F1FE U+1F1EA",
  },
  {
    name: "Mayotte",
    native: "Mayotte",
    phone: "262",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Mamoudzou",
    currency: "EUR",
    languages: ["fr"],
    code: "YT",
    code3: "MYT",
    emoji: "🇾🇹",
    emojiU: "U+1F1FE U+1F1F9",
  },
  {
    name: "South Africa",
    native: "South Africa",
    phone: "27",
    continent: { code: "AF", region: "Southern Africa" },
    capital: "Pretoria",
    currency: "ZAR",
    languages: ["af", "en", "nr", "st", "ss", "tn", "ts", "ve", "xh", "zu"],
    code: "ZA",
    code3: "ZAF",
    emoji: "🇿🇦",
    emojiU: "U+1F1FF U+1F1E6",
  },
  {
    name: "Zambia",
    native: "Zambia",
    phone: "260",
    continent: { code: "AF", region: "Eastern Africa" },
    capital: "Lusaka",
    currency: "ZMW",
    languages: ["en"],
    code: "ZM",
    code3: "ZMB",
    emoji: "🇿🇲",
    emojiU: "U+1F1FF U+1F1F2",
  },
  {
    name: "Zimbabwe",
    native: "Zimbabwe",
    phone: "263",
    continent: { code: "AF", region: "Southern Africa" },
    capital: "Harare",
    currency: "USD,ZAR,BWP,GBP,AUD,CNY,INR,JPY",
    languages: ["en", "sn", "nd"],
    code: "ZW",
    code3: "ZWE",
    emoji: "🇿🇼",
    emojiU: "U+1F1FF U+1F1FC",
  },
] as const satisfies readonly Country[];

export const COUNTRY_NAMES = COUNTRIES.map((c) => c.name);

export type CountryNames = (typeof COUNTRIES)[number]["name"];

export type CountryCodesTwoLetter = (typeof COUNTRIES)[number]["code"];

export type CountryCodesThreeLetter = (typeof COUNTRIES)[number]["code3"];
